spring:
  cassandra:
    keyspace-name: main
    username: ${CASSANDRA_USER_NAME}
    password: ${CASSANDRA_PASSWORD}
    schema-action: recreate_drop_unused
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}


datastax:
  astra:
    secure-connect-bundle: secure-connect.zip